# generate_seed_sql.py
# Generator script to convert questions.json to seed_questions.sql

import json
import os
import sys

def escape_sql_string(val):
    if val is None:
        return "NULL"
    # Double single quotes to escape them in SQL
    escaped = val.replace("'", "''")
    return f"'{escaped}'"

def format_options(opts):
    if opts is None:
        return "NULL"
    # Serialize JSON options and escape single quotes for the SQL literal
    json_str = json.dumps(opts, ensure_ascii=False)
    escaped = json_str.replace("'", "''")
    return f"'{escaped}'::jsonb"

def format_tags(tags):
    if not tags:
        return "'{}'::text[]"
    escaped_tags = [t.replace("'", "''") for t in tags]
    elements = ", ".join(f"'{t}'" for t in escaped_tags)
    return f"ARRAY[{elements}]::text[]"

def generate_sql(json_path, sql_output_path):
    print(f"Reading JSON from: {json_path}")
    if not os.path.exists(json_path):
        print(f"Error: File not found at {json_path}")
        return False
        
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            questions = json.load(f)
    except Exception as e:
        print(f"Error reading JSON: {e}")
        return False

    print(f"Generating SQL seed file for {len(questions)} questions...")
    
    lines = [
        "-- seed_questions.sql",
        "-- Auto-generated by generate_seed_sql.py. Do not edit directly.",
        "",
        "BEGIN;",
        "TRUNCATE TABLE nqt_questions CASCADE;",
        ""
    ]
    
    for idx, q in enumerate(questions):
        # Format variables
        code = escape_sql_string(q.get("code"))
        q_text = escape_sql_string(q.get("question_text"))
        q_img = escape_sql_string(q.get("question_image_url"))
        opts = format_options(q.get("options"))
        ans = escape_sql_string(q.get("correct_answer"))
        expl = escape_sql_string(q.get("explanation"))
        expl_img = escape_sql_string(q.get("explanation_image_url"))
        topic = escape_sql_string(q.get("topic"))
        subtopic = escape_sql_string(q.get("subtopic"))
        diff = f"'{q.get('difficulty')}'::nqt_difficulty"
        sec = f"'{q.get('section')}'::nqt_section"
        q_type = f"'{q.get('question_type')}'::nqt_question_type"
        solve_time = str(q.get("estimated_solve_time"))
        mistakes = escape_sql_string(q.get("common_mistakes"))
        tags = format_tags(q.get("tags"))
        source = f"'{q.get('source')}'::nqt_source_type"
        year = str(q.get("exam_year")) if q.get("exam_year") is not None else "NULL"
        freq = str(q.get("frequency")) if q.get("frequency") is not None else "1"
        verified = "TRUE" if q.get("verified") else "FALSE"
        
        insert_stmt = f"""-- Question #{idx+1} ({q.get('section')} - {q.get('topic')})
INSERT INTO nqt_questions (
    code, question_text, question_image_url, options, correct_answer, 
    explanation, explanation_image_url, topic, subtopic, 
    difficulty, section, question_type, estimated_solve_time, 
    common_mistakes, tags, source, exam_year, frequency, verified
) VALUES (
    {code}, {q_text}, {q_img}, {opts}, {ans}, 
    {expl}, {expl_img}, {topic}, {subtopic}, 
    {diff}, {sec}, {q_type}, {solve_time}, 
    {mistakes}, {tags}, {source}, {year}, {freq}, {verified}
);
"""
        lines.append(insert_stmt)
        
    lines.append("COMMIT;")
    
    os.makedirs(os.path.dirname(sql_output_path), exist_ok=True)
    try:
        with open(sql_output_path, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
        print(f"Successfully generated: {sql_output_path}")
        return True
    except Exception as e:
        print(f"Error writing SQL file: {e}")
        return False

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    json_path = os.path.join(base_dir, "database", "questions.json")
    sql_path = os.path.join(base_dir, "database", "seed_questions.sql")
    success = generate_sql(json_path, sql_path)
    sys.exit(0 if success else 1)
